### ISSUE TITLE
 Manjaro Linux -- Grub theme does not work

### ISSUE THREAD

**Issue by Firestar-Reimu** [xenlism/Grub-themes#1]
https://forum.manjaro.org/t/grub-theme-does-not-work/37524/4

**Comment by geser2008** [comment]
I faced the same issue. The problem was background.jpg file. I converted it to PNG, edit the theme.txt file and it began to work correct.
![background](https://user-images.githubusercontent.com/1221343/99185928-b31f7080-276e-11eb-941b-a48ed78c3bcf.png)

**Comment by GosuSan** [comment]
> I faced the same issue. The problem was background.jpg file. I converted it to PNG, edit the theme.txt file and it began to work correct.

Same problem, fix worked for me, thanks!

**Comment by xenlism** [comment]
Thank I will fix it soon.

ในวันที่ อ. 7 ก.ย. 2021 14:24 น. Tobias Müller ***@***.***>
เขียนว่า:
