### ISSUE TITLE
cant seem to get this working on kali.

### ISSUE THREAD

**Issue by StarMusa88** [xenlism/Grub-themes#12]
cp -r /usr/lib/grub/i386-pc/hwmatch.mod /boot/grub/x86_64-efi/      

Command doesn't seem to work..any suggestions would be appreciated.

**Comment by rahul-797** [comment]
> cp -r /usr/lib/grub/i386-pc/hwmatch.mod /boot/grub/x86_64-efi/
> 
> Command doesn't seem to work..any suggestions would be appreciated.

have you tried with sudo?
