### ISSUE TITLE
Problem using Ubuntu 1080 Grub Theme with a 1920x1200 monitor

### ISSUE THREAD

**Issue by sardus-X** [xenlism/Grub-themes#3]
Hi,
I manually installed (copying the Xenlism-Ubuntu folder in /boot/grub/themes and modifying the /etc/default/grub file accordingly) Your GRUB theme (Xenlism-Ubuntu 1080 v.) on my system that uses a monitor with max resolution 1920x1200.
The theme seems to work but the Ubuntu logo is distorted (oval and not circular).
The are the GRUB settings in /etc/default/grub file:

`GRUB_DEFAULT=0  

GRUB_TIMEOUT_STYLE=hidden

GRUB_TIMEOUT="-1"

GRUB_DISTRIBUTOR=`lsb_release -i -s 2> /dev/null || echo Debian`

GRUB_CMDLINE_LINUX_DEFAULT="quiet splash"

GRUB_CMDLINE_LINUX=""

GRUB_THEME=/boot/grub/themes/Xenlism-Ubuntu/theme.txt
`
How could I correct this problem?
Also, could you please add the KDE-Neon distribution icon to the existing ones?
Thanks in advance for Your help

**Comment by xenlism** [comment]
You have to set resolution in grub config file to 1920*1080*32

ในวันที่ จ. 4 ต.ค. 2021 22:31 น. sardus-X ***@***.***>
เขียนว่า:

**Comment by sardus-X** [comment]
Sorry, but running `videoinfo` in grub console mode 1920x1080x32 it is not among the resolutions supported on my system: can it still be used without problems?

**Comment by xenlism** [comment]
Change Resolution ratio to 16:9
Maybe 1280 x 800

ในวันที่ อ. 5 ต.ค. 2021 20:41 น. sardus-X ***@***.***>
เขียนว่า:
