### ISSUE TITLE
Please convert all the JPEG to PNGs

### ISSUE THREAD

**Issue by grohan47** [xenlism/Grub-themes#5]
Leaving the backgrounds as JPEGs seem to be causing a lot of problems. Please export and replace all the JPEGs with PNGs, preferably straight from whatever image editor you have used rather than converting them online.

**Comment by xenlism** [comment]
Thank for your information.

ในวันที่ พ. 20 เม.ย. 2022 17:30 น. grohan47 ***@***.***>
เขียนว่า:
