### ISSUE TITLE
Arch 1080 -> background.png instead of backgroud.png

### ISSUE THREAD

**Issue by mblob** [xenlism/Grub-themes#7]
Hi,
First thanks for your work. Then check tht little problem.
rename backgroud.png to backgrou**n**d.png
![image](https://github.com/xenlism/Grub-themes/assets/967684/60251e6e-d0f9-4543-b910-5ec1fa5f7768)

**Comment by xenlism** [comment]
Thank You
I will update soon.

ในวันที่ พ. 24 พ.ค. 2023 03:43 น. mblob ***@***.***> เขียนว่า:
