### ISSUE TITLE
Fedora don't detected after install 

### ISSUE THREAD

**Issue by kevinalfito69** [xenlism/Grub-themes#9]
I downloaded xenlim-grub-4k-fedora theme and, I install this theme using command ```sudo ./install.sh ``` When I restarted my grub didn't detect my fedora os, Is there any solution?

**Comment by rahul-797** [comment]
> I downloaded xenlim-grub-4k-fedora theme and, I install this theme using command `sudo ./install.sh ` When I restarted my grub didn't detect my fedora os, Is there any solution?

try this command `os-prober`
it will search for OS and add them to grub
